export const valuesOfPropertyForm = {
    typeOfService: [
        { label: 'Аренда', value: 'Аренда' },
        { label: 'Продажа', value: 'Продажа' },
    ],
    propertyCity: [
        { label: 'Арамболь', value: 'Арамболь' },
        { label: 'Гоа', value: 'Гоа' },
        { label: 'Делли', value: 'Делли' },
        { label: 'Керим', value: 'Керим' },
        { label: 'Мандрем', value: 'Мандрем' },
        { label: 'Морджим', value: 'Морджим' },
        { label: 'Мумбай', value: 'Мумбай' },
        { label: 'Панаджи', value: 'Панаджи' },
    ],
    balcony: ['Есть', 'Нет', 'Лоджия'],
    roomsQuantity: [1, 2, 3, 4],
    propertyDistrict: [
        { label: 'Верхний', value: 'Верхний' },
        { label: 'Нижний', value: 'Нижний' },
        { label: 'Левый', value: 'Левый' },
        { label: 'Правый', value: 'Правый' },
    ],
    bathroomType: ['Совмещенный', 'Раздельный'],
    houseType: [
        { label: 'Панельный', value: 'Панельный' },
        { label: 'Кирпичный', value: 'Кирпичный' },
        { label: 'Деревянный', value: 'Деревянный' },
        { label: 'Блочный', value: 'Блочный' },
    ],
    prepayment: [
        { value: 'Без предоплаты', label: 'Без предоплаты' },
        { value: 'Месяц', label: 'Месяц' },
        { value: 'Два месяца', label: 'Два месяца' },
        { value: 'Три месяца', label: 'Три месяца' },
        { value: 'Пол года', label: 'Пол года' },
    ],
    rentalCondition: [
        { label: 'Семье', value: 'Семье' },
        { label: 'Для одного', value: 'Для одного' },
        { label: 'Девушке', value: 'Девушке' },
        { label: 'Под офис', value: 'Под офис' },
        { label: 'Студентам', value: 'Студентам' },
        { label: 'Не компаниям', value: 'Не компаниям' },
    ],
    amenities: ['Wi-fi', 'Кондиционер', 'Увлажнитель', 'Сейф', 'Телевизор'],
    typeOfProperty: [
        { label: 'Квартира', value: 'Квартира' },
        { label: 'Комната', value: 'Комната' },
        { label: 'Дом', value: 'Дом' },
    ],
};
// {label: '', value: ''},
