version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    command: sh -c "npm install serve -g && npm run build && npm run serve"
    depends_on:
      - backend
    ports:
      - 3000:3000
