version: "3.8"

services:
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/usr/scr/app
        ports:
          - "8000:8000"

        depends_on:
          - pgdb
    pgdb:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
          - pgdata:/var/lib/postgres/data/
volumes:
    pgdata:



