# Generated by Django 4.2.5 on 2023-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForbiddenWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("russian_words", models.TextField(verbose_name="Русские слова")),
                ("english_words", models.TextField(verbose_name="Английские слова")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
