# Generated by Django 4.2.5 on 2024-01-05 11:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForbiddenWords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "russian_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50, verbose_name="Русские слова"),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "english_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50, verbose_name="Английские слова"),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрещенны слова",
            },
        ),
    ]
