export const valuesOfTransportForm = {
    transport_type_of_service: ['Аренда', 'Продажа'],
    transport_type: ['Наземный', 'Водный'],
    transport_category: [
        { value: 'motorcycle', label: 'Мотоцикл' },
        { value: 'moped', label: 'Мопед' },
        { value: 'car', label: 'Легковой автомобиль' },
        { value: 'truck', label: 'Грузовой автомобиль' },
        { value: 'bus', label: 'Автобус' },
        { value: 'tricycle', label: 'Трицикл' },
        { value: 'trailer', label: 'Трэйлер' },
        { value: 'roadhouse', label: 'Дом на колесах' },
        { value: 'motorboat', label: 'Моторная лодка' },
        { value: 'oar_boat', label: 'Вёсельная лодка' },
        { value: 'boat', label: 'Катер' },
        { value: 'other', label: 'Другое' },
    ],
    transport_brand: [
        { value: '2', label: 'Yamaha' },
        { value: '4', label: 'BMW' },
        { value: '3', label: 'Mazda' },
        { value: '1', label: 'Toyota' },
    ],
    transport_model: [
        { value: '4', label: 'Camry' },
        { value: '1', label: '1' },
        { value: '2', label: '2' },
        { value: '3', label: '3' },
        { value: '5', label: 'Land Cruizer' },
        { value: '7', label: 'TDM-850' },
        { value: '6', label: 'TDM-900' },
    ],
    transport_engine_type: [
        { label: 'Бензиновый', value: 'fuel' },
        { label: 'Дизельный', value: 'diesel' },
        { label: 'Газовый', value: 'gas' },
        { label: 'Электрический', value: 'electric' },
        { label: 'Гибрид', value: 'hybrid' },
    ],
    transport_drive_type: [
        { value: 'front_wheel', label: 'Передний' },
        { value: 'rear_wheel', label: 'Задний' },
        { value: 'all_wheel', label: 'Постоянный полный' },
        { value: 'four_wheel', label: 'Подключаемый полный' },
    ],
    transport_transmission_type: [
        { value: 'mechanic', label: 'Механическая' },
        { value: 'automatic', label: 'Автоматическая' },
        { value: 'robot', label: 'Робот' },
        { value: 'cvt', label: 'Вариатор' },
    ],
    transport_body_type: [
        { label: 'Седан', value: 'sedan' },
        { label: 'Хэтчбэк', value: 'hatchback' },
        { label: 'Лифтбэк', value: 'liftback' },
        { label: 'Купе', value: 'coupe' },
        { label: 'Кабриолет', value: 'convertible' },
        { label: 'Внедорожник', value: 'suv' },
        { label: 'Лимузин', value: 'limousine' },
        { label: 'Пикап', value: 'pickup' },
    ],
    transport_condition: [
        { label: 'Новый', value: 'new' },
        { label: 'Б/у', value: 'used' },
        { label: 'Аварийный', value: 'salvage' },
        { label: 'На запчасти', value: 'spare' },
    ],
};
