export const valuesOfTransportForm = {
    typeOfService: ['Аренда', 'Продажа'],
    typeOfTransport: ['Наземный', 'Водный'],
    transportationCategory: [
        { value: 'Мотоцикл', label: 'Мотоцикл' },
        { value: 'Мопед', label: 'Мопед' },
        { value: 'Легковой автомобиль', label: 'Легковой автомобиль' },
        { value: 'Грузовой автомобиль', label: 'Грузовой автомобиль' },
        { value: 'Автобус', label: 'Автобус' },
        { value: 'Трицикл', label: 'Трицикл' },
        { value: 'Трэйлер', label: 'Трэйлер' },
        { value: 'Дом на колесах', label: 'Дом на колесах' },
        { value: 'Моторная лодка', label: 'Моторная лодка' },
        { value: 'Вёсельная лодка', label: 'Вёсельная лодка' },
        { value: 'Катер', label: 'Катер' },
        { value: 'Другое', label: 'Другое' },
    ],
    mark: [
        { value: 'BMW', label: 'BMW' },
        { value: 'Mazda', label: 'Mazda' },
        { value: 'Toyota', label: 'Toyota' },
        { value: 'Yamaha', label: 'Yamaha' },
    ],
    model: [{ value: 'Fascino', label: 'Fascino' }],
    engineType: [
        { label: 'Бензиновый', value: 'Бензиновый' },
        { label: 'Дизельный', value: 'Дизельный' },
        { label: 'Газовый', value: 'Газовый' },
        { label: 'Электрический', value: 'Электрический' },
        { label: 'Гибрид', value: 'Гибрид' },
    ],
    drive: ['Передний', 'Задний', 'Постоянный полный', 'Полный подключаемый'],
    transmissionType: ['МКПП', 'АКПП', 'Робот', 'Вариатор'],
    bodyType: [
        { label: 'Седан', value: 'Седан' },
        { label: 'Хэтчбэк', value: 'Хэтчбэк' },
        { label: 'Лифтбэк', value: 'Лифтбэк' },
        { label: 'Купе', value: 'Купе' },
        { label: 'Кабриолет', value: 'Кабриолет' },
        { label: 'Внедорожник', value: 'Внедорожник' },
        { label: 'Лимузин', value: 'Лимузин' },
        { label: 'Пикап', value: 'Пикап' },
    ],
    condition: ['Новый', 'Б/у', 'Аварийный', 'На запчасти'],
};
