# Generated by Django 4.2.5 on 2023-10-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='property_amenities',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='offers.propertyamenity', verbose_name='Удобства'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='proposed_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_currency_pairs', to='offers.currency', verbose_name='Предлагаемая валюта'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transport_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.transportbrand', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transport_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.transportmodel', verbose_name='Модель'),
        ),
    ]
