# Generated by Django 4.2.5 on 2023-09-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='transport_body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Седан'), ('liftback', 'Лифтбэк'), ('coupe', 'Купе'), ('convertible', 'Кабриолет'), ('hatchback', 'Хэтчбэк'), ('SUV', 'Внедорожник'), ('limousine', 'Лимузин'), ('pickup', 'Пикап')], max_length=50, null=True, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_brand',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_category',
            field=models.CharField(blank=True, choices=[('motorcycle', 'Мотоцикл'), ('moped', 'Мопед'), ('car', 'Легковой автомобиль'), ('truck', 'Грузовой автомобиль'), ('bus', 'Автобус'), ('tricycle', 'Трицикл'), ('trailer', 'Трэйлер'), ('roadhouse', 'Дом на колёсах'), ('motorboat', 'Моторная лодка'), ('oar_boat', 'Вёсельная лодка'), ('boat', 'Катер'), ('other', 'Другое')], max_length=50, null=True, verbose_name='Категория транспорта'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_condition',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/у'), ('salvage', 'Аварийный'), ('spare', 'На запчасти')], max_length=100, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_drive_type',
            field=models.CharField(blank=True, choices=[('front_wheel', 'Передний'), ('rear_wheel', 'Задний'), ('all_wheel', 'Постоянный полный'), ('four_wheel', 'Подключаемый полный')], max_length=50, null=True, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_engine_type',
            field=models.CharField(blank=True, choices=[('fuel', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электричество'), ('hybrid', 'Гибрид')], max_length=100, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_model',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_transmission_type',
            field=models.CharField(blank=True, choices=[('mechanic', 'Механическая'), ('automatic', 'Автоматическая')], max_length=50, null=True, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('ground', 'Наземный'), ('water', 'Водный')], max_length=50, null=True, verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_type_of_service',
            field=models.CharField(blank=True, choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=25, null=True, verbose_name='Тип услуги'),
        ),
    ]
