# Generated by Django 4.2.5 on 2023-10-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="property_rental_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("family", "Семье"),
                    ("alone", "Для одного"),
                    ("girls", "Девушке"),
                    ("office", "Под офис"),
                    ("students", "Студентам"),
                    ("not_companies", "Не компаниям"),
                ],
                max_length=100,
                verbose_name="Условия аренды",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="transport_transmission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mechanic", "Механическая"),
                    ("automatic", "Автоматическая"),
                    ("robot", "Робот"),
                ],
                max_length=50,
                null=True,
                verbose_name="Тип коробки передач",
            ),
        ),
    ]
