# Generated by Django 4.2.5 on 2023-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='subcategory',
            field=models.CharField(choices=[('property', 'Недвижимость'), ('transport', 'Транспорт')], verbose_name='Подкатегории'),
        ),
    ]
