# Generated by Django 4.2.5 on 2023-09-17 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель модели'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.product', verbose_name='Товар'),
        ),
    ]
