# Generated by Django 4.2.5 on 2023-09-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='product',
        ),
        migrations.AddField(
            model_name='attributes',
            name='product',
            field=models.ManyToManyField(to='offers.product'),
        ),
    ]
