# Generated by Django 4.2.5 on 2023-09-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_advertisement_product_remove_attributes_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(to='offers.attributes'),
        ),
    ]
