# Generated by Django 4.2.5 on 2023-09-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0002_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='attributes',
            field=models.ManyToManyField(related_name='advertisements', to='offers.attribute', verbose_name='Аттрибуты'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='advertisements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.advertisement', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='offers/image/photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='offers.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
