# Generated by Django 4.2.5 on 2023-09-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='buy_sell_product',
            new_name='buy_sell_item',
        ),
    ]
