# Generated by Django 4.2.5 on 2023-10-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(max_length=3, unique=True, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transport_vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN-номер'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.CharField(choices=[('property', 'Недвижимость'), ('transport', 'Транспорт'), ('job', 'Работа'), ('service', 'Услуги'), ('taxi', 'Такси'), ('event', 'События'), ('exchange_rate', 'Обмен валюты')], max_length=100, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='property_amenities',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='offers.propertyamenity', verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.transportbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='transport_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.transportmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='exchange_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_for_currency_pairs', to='offers.currency', verbose_name='Обмен на'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='proposed_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_currency_pairs', to='offers.currency', verbose_name='Предлагаемая валюта'),
        ),
    ]
