# Generated by Django 4.2.5 on 2023-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_currency_advertisement_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.UniqueConstraint(fields=('owner', 'proposed_currency', 'exchange_for'), name='owner_proposed_currency_exchange_for_unique_together'),
        ),
    ]
