# Generated by Django 4.2.5 on 2023-09-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_buy_sell_product_advertisement_buy_sell_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='buy_sell_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offers.item', verbose_name='Товар'),
        ),
    ]
