# Generated by Django 4.2.5 on 2023-09-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_advertisement_description'),
    ]

    operations = [
    ]
