# Generated by Django 4.2.5 on 2023-09-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_advertisement_options_alter_attributes_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attributes',
            new_name='Attribute',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='property',
            new_name='advertisements',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Транслит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='offers.subcategory'),
        ),
    ]
