# Generated by Django 4.2.5 on 2023-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_merge_20230925_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='property_rooms_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество комнат'),
        ),
    ]
