# Generated by Django 4.2.5 on 2023-09-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_advertisement_buy_sell_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='offers.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование услуги'),
        ),
    ]
