# Generated by Django 4.2.5 on 2023-09-30 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_advertisement_service_name_alter_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
