# Generated by Django 4.2.5 on 2023-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_advertisement_property_rooms_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала'),
        ),
    ]
