# Generated by Django 4.2.5 on 2023-09-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_remove_advertisement_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='event_theme',
        ),
        migrations.DeleteModel(
            name='EventTheme',
        ),
    ]
