# Generated by Django 4.2.5 on 2023-09-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_advertisement_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='contact',
            new_name='owner',
        ),
    ]
