# Generated by Django 4.2.5 on 2023-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_advertisement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
