# Generated by Django 4.2.5 on 2023-09-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_advertisement_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='buy_sell_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='offers.item', verbose_name='Товар'),
        ),
    ]
