# Generated by Django 4.2.5 on 2023-09-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_advertisement_buy_sell_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='service_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='offers.service'),
        ),
    ]
