# Generated by Django 4.2.5 on 2023-11-11 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_alter_advertisement_job_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "ordering": ("-date_create",),
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
    ]
