# Generated by Django 4.2.5 on 2023-11-11 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0003_advertisement_property_commission_and_more"),
        ("offers", "0003_alter_advertisement_job_duration_and_more"),
    ]

    operations = []
