# Generated by Django 4.2.5 on 2023-10-24 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0003_review_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Отзыв')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('advertisement_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Создатель объявления')),
                ('review_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
