# Generated by Django 4.2.5 on 2023-10-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_rate_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='review_author',
            new_name='rate_author',
        ),
    ]
