# Generated by Django 4.2.5 on 2023-11-11 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_alter_advertisement_options"),
        ("offers", "0004_merge_20231111_1602"),
    ]

    operations = []
