# Generated by Django 4.2.5 on 2023-11-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_merge_20231111_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Недвижимость - Города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PropertyDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_districts', to='offers.propertycity', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Недвижимость - Районы',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='property_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.propertycity', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='property_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='offers.propertydistrict', verbose_name='Район'),
        ),
    ]
