# Generated by Django 4.2.5 on 2023-10-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_review_author_rate_rate_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
