# Generated by Django 4.2.5 on 2023-11-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0005_merge_20231111_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="document_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("month", "Месяц"),
                    ("quarter", "Квартал"),
                    ("year", "Год"),
                    ("years_5", "5 лет"),
                    ("other", "Другое"),
                ],
                max_length=50,
                verbose_name="Срок действия",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tourist-visa", "Туристская виза"),
                    ("business-visa", "Бизнес-виза"),
                    ("c-form", "C-форма"),
                    ("exit-permit", "Продление выезда"),
                    ("other", "Другое"),
                ],
                max_length=50,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="establishment",
            field=models.BooleanField(default=False, verbose_name="Ресторан/кафе"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="excursion_food",
            field=models.BooleanField(default=False, verbose_name="Включена еда"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="excursion_transfer",
            field=models.BooleanField(default=False, verbose_name="Трансфер"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="food_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("veg_food", "Вегетарианская еда"),
                    ("non_veg_food", "Невегетарианская еда"),
                    ("ready_food", "Готовая еда"),
                    ("semi_finished_food", "Полуфабрикаты"),
                    ("other_food", "Другое"),
                ],
                max_length=50,
                verbose_name="Тип еды",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="market_condition",
            field=models.CharField(
                blank=True,
                choices=[("new", "Новое"), ("used", "Б/У")],
                max_length=25,
                null=True,
                verbose_name="Состояние",
            ),
        ),
    ]
