# Generated by Django 4.2.5 on 2023-11-18 15:33

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_propertycity_propertydistrict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, verbose_name='Координаты'),
        ),
    ]
