# Generated by Django 4.2.5 on 2023-11-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_advertisement_document_duration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="establishment",
            new_name="food_establishment",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="food_delivery",
            field=models.BooleanField(default=False, verbose_name="Доставка на дом"),
        ),
    ]
