# Generated by Django 4.2.5 on 2023-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "offers",
            "0007_rename_establishment_advertisement_food_establishment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="category",
            field=models.CharField(
                choices=[
                    ("property", "Недвижимость"),
                    ("transport", "Транспорт"),
                    ("job", "Работа"),
                    ("service", "Услуги"),
                    ("taxi", "Такси"),
                    ("event", "События"),
                    ("exchange_rate", "Обмен валюты"),
                    ("market", "Купить-продать"),
                    ("document", "Документы"),
                    ("food", "Еда"),
                    ("excursion", "Экскурсии"),
                ],
                max_length=100,
                verbose_name="Категории",
            ),
        ),
    ]
