# Generated by Django 4.2.5 on 2023-11-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_advertisement_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyamenity',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Слаг'),
        ),
    ]
