# Generated by Django 4.2.5 on 2023-11-21 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0008_alter_advertisement_category"),
        ("offers", "0009_remove_advertisement_property_coords"),
    ]

    operations = []
