# Generated by Django 4.2.5 on 2023-11-25 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0010_merge_20231121_1031"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="home_visit",
            new_name="service_home_visit",
        ),
    ]
