# Generated by Django 4.2.5 on 2023-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0011_rename_home_visit_advertisement_service_home_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flat", "Квартира"),
                    ("house", "Дом"),
                    ("room", "Комната"),
                    ("bed_place", "Кровать"),
                    ("parking", "Парковочное место"),
                    ("commercial", "Коммерческое помещение"),
                ],
                max_length=50,
                verbose_name="Тип собственности",
            ),
        ),
    ]
