# Generated by Django 4.2.5 on 2023-12-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
        ("offers", "0012_advertisement_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisement",
                to="countries.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisement",
                to="countries.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisement",
                to="countries.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Цена"
            ),
        ),
    ]
