# Generated by Django 4.2.5 on 2024-01-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_advertisement_city_advertisement_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydistrict',
            name='city',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='property_city',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='property_district',
        ),
        migrations.DeleteModel(
            name='PropertyCity',
        ),
        migrations.DeleteModel(
            name='PropertyDistrict',
        ),
    ]
