# Generated by Django 4.2.5 on 2024-01-13 09:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0014_remove_propertydistrict_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="slug",
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
