# Generated by Django 4.2.5 on 2024-02-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0015_alter_advertisement_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="youtube",
            field=models.URLField(
                blank=True,
                help_text="https://www.youtube.com/watch?v=jNQXAC9IVRw",
                max_length=60,
                null=True,
                verbose_name="Ссылка на ютуб",
            ),
        ),
    ]
