# Generated by Django 4.2.5 on 2024-03-05 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0016_advertisement_youtube"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="transport_engine_volume",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(9.9),
                ],
                verbose_name="Объём",
            ),
        ),
    ]
