# Generated by Django 4.2.5 on 2024-03-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0019_alter_advertisement_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="property_rent_duration",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Посуточно"), ("per_months", "Помесячно")],
                max_length=50,
                null=True,
                verbose_name="Срок аренды",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="transport_rent_duration",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Посуточно"), ("per_months", "Помесячно")],
                max_length=50,
                null=True,
                verbose_name="Срок аренды",
            ),
        ),
    ]
