# Generated by Django 4.2.5 on 2024-03-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_advertisement_property_rent_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportbrand',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='transportmodel',
            name='ref_id',
        ),
    ]
