# Generated by Django 4.2.5 on 2024-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0021_remove_transportbrand_ref_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="transport_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("motorcycle", "Мотоцикл"),
                    ("car", "Легковой автомобиль"),
                    ("truck", "Грузовой автомобиль"),
                    ("bus", "Автобус"),
                    ("tricycle", "Трицикл"),
                    ("trailer", "Трэйлер"),
                    ("roadhouse", "Дом на колёсах"),
                    ("motorboat", "Моторная лодка"),
                    ("oar_boat", "Вёсельная лодка"),
                    ("boat", "Катер"),
                    ("other", "Другое"),
                ],
                max_length=50,
                null=True,
                verbose_name="Категория транспорта",
            ),
        ),
        migrations.AlterField(
            model_name="transportmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("motorcycle", "Мотоцикл"),
                    ("car", "Легковой автомобиль"),
                    ("truck", "Грузовой автомобиль"),
                    ("bus", "Автобус"),
                    ("tricycle", "Трицикл"),
                    ("trailer", "Трэйлер"),
                    ("roadhouse", "Дом на колёсах"),
                    ("motorboat", "Моторная лодка"),
                    ("oar_boat", "Вёсельная лодка"),
                    ("boat", "Катер"),
                    ("other", "Другое"),
                ],
                max_length=50,
                null=True,
                verbose_name="Категория транспорта",
            ),
        ),
    ]
