# Generated by Django 4.2.5 on 2024-11-05 15:36

from django.db import migrations, models
from offers.utils import get_file_size_in_megabytes


def generate_images_sizes(apps, schema_editor) -> None:
    """Сгенерировать PropertyPromoType и добавить всем акциям."""
    AdvertisementImage = apps.get_model("offers", "AdvertisementImage")
    images_update_list: list[AdvertisementImage] = []
    for _ in AdvertisementImage.objects.all():
        _.size = get_file_size_in_megabytes(_.image)
        images_update_list.append(_)

    AdvertisementImage.objects.bulk_update(objs=images_update_list, fields=["size"])


def rollback_generate_images_sizes(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0022_alter_advertisement_transport_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementimage',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Размер фотографии (в МБ)'),
        ),
        migrations.RunPython(
            code=generate_images_sizes,
            reverse_code=rollback_generate_images_sizes,
        )
    ]
