# Generated by Django 4.2.5 on 2024-11-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0023_advertisementimage_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="description",
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name="Описание"),
        ),
    ]
