# Generated by Django 4.2.5 on 2024-02-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers", "0015_alter_advertisement_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("offer_not_current", "Товар продан"),
                            ("not_censored", "Не цензурные выражения"),
                            ("prohibited_substances", "Запрещенные вещества"),
                            ("scammer", "Мошенник"),
                            ("wrong_description", "Неверное описание/фото"),
                            ("wrong_location", "Неверная локация"),
                            ("wrong_price", "Неверная цена"),
                            ("other", "Другое"),
                        ],
                        max_length=50,
                        verbose_name="Причина жалобы",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=900, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_to_advertisement",
                        to="offers.advertisement",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_to_advertisement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="От пользователя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жалоба",
                "verbose_name_plural": "Жалобы",
            },
        ),
        migrations.AddConstraint(
            model_name="reportmodel",
            constraint=models.UniqueConstraint(
                fields=("from_user", "advertisement"), name="unique_user_report"
            ),
        ),
    ]
