# Generated by Django 4.2.5 on 2024-02-14 19:17

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartnerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="Название")),
                ("description", models.CharField(max_length=300, verbose_name="Описание")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=150, null=True, verbose_name="Ссылка на партнера"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("slug", autoslug.fields.AutoSlugField(unique=True)),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
                "ordering": ("-date_create",),
            },
        ),
        migrations.CreateModel(
            name="PartnerImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="partners/image", verbose_name="Фотография"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="partners.partnermodel",
                        verbose_name="Партнеры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
