# Generated by Django 4.2.5 on 2023-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user_rated',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user_being_rated',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
