# Generated by Django 4.2.5 on 2024-01-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_rate_options_alter_rate_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('from_user', 'to_user')},
        ),
    ]
