# Generated by Django 4.2.5 on 2024-01-24 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_rate_from_user_alter_rate_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "link_to_messenger",
                    models.CharField(max_length=100, verbose_name="Ссылка на мессенджер"),
                ),
            ],
            options={
                "verbose_name": "Мессенджер",
                "verbose_name_plural": "Мессенджеры",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="UserMessenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "link_to_user",
                    models.CharField(max_length=150, verbose_name="Ссылка на пользователя"),
                ),
                (
                    "messenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_messengers",
                        to="users.messenger",
                        verbose_name="Мессенджер",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_messengers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мессенджер пользователя",
                "verbose_name_plural": "Мессенджеры пользователей",
                "ordering": ("owner",),
            },
        ),
    ]
