# Generated by Django 4.2.5 on 2024-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_messenger_usermessenger_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messenger",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Описание"),
        ),
    ]
