name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Cloning repository
      - name: Clone repo
        uses: actions/checkout@v4

      # DB
      - name: Pull db
        run: docker compose -f docker-compose.yml pull db || true

      - name: Build db
        run: docker compose -f docker-compose.yml build db

      - name: Push db
        run: docker compose -f docker-compose.yml push db

      # Backend
      - name: Pull backend
        run: docker compose -f docker-compose.yml pull backend || true

      - name: Build backend
        run: docker compose -f docker-compose.yml build backend

      - name: Push backend
        run: docker compose -f docker-compose.yml push backend

      # Frontend
      - name: Pull frontend
        run: docker compose -f docker-compose.yml -f docker-compose.frontend.yml pull frontend || true

      - name: Build frontend
        run: docker compose -f docker-compose.yml -f docker-compose.frontend.yml build frontend

      - name: Push frontend
        run: docker compose -f docker-compose.yml -f docker-compose.frontend.yml push frontend

      # Nginx
      - name: Pull nginx
        run: docker compose -f docker-compose.yml pull nginx || true

      - name: Build nginx
        run: docker compose -f docker-compose.yml build nginx

      - name: Push nginx
        run: docker compose -f docker-compose.yml push nginx

  tests:
    runs-on: ubuntu-latest
    environment: production
    needs: [ build ]

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Pull backend
        run: docker compose -f docker-compose.yml pull backend || true

      - name: Test backend
        run: docker compose -f docker-compose.yml run --rm backend /bin/sh -c "pytest -p no:warnings --cov-report term:skip-covered --cov=."
